const API_KEY = 'AIzaSyDhCnfezRndQ-yTdC5oJ4a9ifOrPl_7J18';
const SPREADSHEET_ID = '1NKnaATTKPDGZ0s8MXoNX7mcUgQ8WsSIz7hBWZ24ZMdg';

//ACA IRIAN LOS SERVICIOS: OBTENER DATOS (GENERAL) - OBTENER CAFÉS, OBTENER LIBROS Y OBTENER PREGUNTAS FRECUENTES